turn off package mode for tool.poetry for streamlit deployment (#22)
remove this error from streamlit deployment

Error
```
Installing the current project: snack-stack-ai-fvela (0.0.1)
Error: The current project could not be installed: No file/folder found for package snack-stack-ai-fvela
If you do not want to install the current project use --no-root.
If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file.
If you did intend to install the current project, you may need to set `packages` in your pyproject.toml file.
/mount/src/snack-stack-ai
```