add poetry package for streamlit deploy (#23)
It turns out we do need to install the packages when we deploy to
streamlit. It was not a requirement in local deployment.

error examples 
```
────────────────────────────────────────────────────────────────────────────────
ModuleNotFoundError: No module named 'frontend'
────────────────────── Traceback (most recent call last) ───────────────────────
  /home/adminuser/venv/lib/python3.11/site-packages/streamlit/runtime/scriptru  
  nner/exec_code.py:136 in exec_func_with_error_handling                        
                                                                                
  /home/adminuser/venv/lib/python3.11/site-packages/streamlit/runtime/scriptru  
  nner/script_runner.py:825 in code_to_exec                                     
                                                                                
  /home/adminuser/venv/lib/python3.11/site-packages/streamlit/runtime/scriptru  
  nner/script_runner.py:168 in _mpa_v1                                          
                                                                                
  /home/adminuser/venv/lib/python3.11/site-packages/streamlit/navigation/page.  
  py:494 in run                                                                 
                                                                                
  /mount/src/snack-stack-ai/src/frontend/app.py:5 in <module>                   
                                                                                
      2 import json                                                             
      3                                                                         
      4 import streamlit as st                                                  
  ❱   5 from frontend.utils.common import (                                     
      6   CONFIG_ERROR_MESSAGE,                                                 
      7   CONFIG_FAILED,                                                        
      8   MENU_CONFIG,    
```

## Tests
### Poetry check
```
poetry check
All set!
```
### Poetry build
```
poetry build
Building snack-stack-ai-fvela (0.0.1)
Building sdist
Building wheel
```

### Poetry install
```
poetry install
Updating dependencies
Resolving dependencies... (46.5s)

Package operations: 0 installs, 1 update, 0 removals

  - Downgrading networkx (3.6.1 -> 3.6)

Writing lock file

Installing the current project: snack-stack-ai-fvela (0.0.1)
```